### ISSUE TITLE
Type 'unknown' is not assignable to type 'State'

### ISSUE THREAD

**Issue by hwalker928** [pterodactyl/panel#3134]
**Background (please complete the following information):**
* Panel or Daemon: Panel
* Version of Panel/Daemon: 1.2.2
* Server's OS: Ubuntu 20.04
* Your Computer's OS & Browser: N/A

**Describe the bug**
When running `npm run build:production`, this error gets thrown out.
```
ERROR in resources/scripts/components/dashboard/AccountOverviewContainer.tsx:32:14
TS2571: Object is of type 'unknown'.
    30 |     return (
    31 |         <PageContentBlock title={'Account Overview'}>
  > 32 |             {state?.twoFactorRedirect &&
       |              ^^^^^
    33 |             <MessageBox title={'2-Factor Required'} type={'error'}>
    34 |                 Your account must have two-factor authentication enabled in order to continue.
    35 |             </MessageBox>

ERROR in resources/scripts/components/dashboard/AccountOverviewContainer.tsx:37:42
TS2571: Object is of type 'unknown'.
    35 |             </MessageBox>
    36 |             }
  > 37 |             <Container css={[ tw`mb-10`, state?.twoFactorRedirect ? tw`mt-4` : tw`mt-10` ]}>
       |                                          ^^^^^
    38 |                 <ContentBox title={'Update Password'} showFlashes={'account:password'}>
    39 |                     <UpdatePasswordForm/>
    40 |                 </ContentBox>

ERROR in resources/scripts/components/server/schedules/ScheduleEditContainer.tsx:51:11
TS2322: Type 'unknown' is not assignable to type 'State'.
    49 |     const params = useParams() as Params;
    50 |     const history = useHistory();
  > 51 |     const state: State = useLocation().state;
       |           ^^^^^
    52 |
    53 |     const id = ServerContext.useStoreState(state => state.server.data!.id);
    54 |     const uuid = ServerContext.useStoreState(state => state.server.data!.uuid);
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! pterodactyl-panel@ build:production: `yarn run clean && cross-env NODE_ENV=production ./node_modules/.bin/webpack --mode production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the pterodactyl-panel@ build:production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-02T16_57_36_162Z-debug.log
root@harryvps:/var/www/pterodactyl#
```
I did not modify anything to do with states.

**To Reproduce**
N/A

**Expected behavior**
The build goes through without any errors.

**Comment by DaneEveritt** [comment]
Please indicate the _exact_ version, "latest" changes daily and is not a helpful version.

**Comment by hwalker928** [comment]
1.2.2

**Comment by mason-rogers** [comment]
What node/npm version?

**Comment by hwalker928** [comment]
```
root@harryvps:/var/www/pterodactyl# npm -v
6.14.4
root@harryvps:/var/www/pterodactyl# node -v
v10.19.0
root@harryvps:/var/www/pterodactyl#
```

Just updated to node 12, same error.

**Comment by DaneEveritt** [comment]
You should upgrade to Node 14, delete `node_modules` and try again. Multiple people use develop for work and have had no issues, and multiple people have worked on 1.2.2 without issues. This leads me to believe you did make modifications, even if unintentional, that are affecting your ability to compile.

**Comment by hwalker928** [comment]
Okay, I have got further. I am now getting a `TypeError: a._init is not a function` error in the console with An error was encountered by the application while rendering this view. Try refreshing the page.

**Comment by notAreYouScared** [comment]
I've only seen that error when `yarn upgrade` is ran. You shouldn't upgrade the packages as the above will happen.

**Comment by hwalker928** [comment]
Okay, building with node 14 works fine, but I am still getting the `TypeError: a._init is not a function`
![image](https://user-images.githubusercontent.com/63236817/109703051-ef93a280-7b8c-11eb-83fa-d2d2d6c8cdd2.png)

**Comment by notAreYouScared** [comment]
Please delete the `node_modules` `yarn.lock` and the `package.json` and get the new one from here https://github.com/pterodactyl/panel/tree/release/v1.2.2

Then redo `yarn install` then build your assets

**Comment by DaneEveritt** [comment]
Closing this because it appears to be user error and nothing to do with our process.
